import type { Metadata } from "next";
import { Rubik, Source_Sans_3 } from "next/font/google";
import "./globals.css";

// Fonte do titulo
const fontRubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  // 400 = normal, 500 = medium, 700 = bold, 800 = extrabold
});

// Fonte do texto
const fontSource_Sans_3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  // 400 = normal, 500 = medium, 700 = bold, 800 = extrabold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${fontRubik.variable} ${fontSource_Sans_3.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
